export default {
  SPLASH: 'SPLASH',
  ONBOARDING: 'ONBOARDING',
  LOGIN: 'LOGIN',
  SIGNUP: 'SIGNUP',
  VERIFYOTP: 'VERIFYOTP',
  ACCOUNTCONFIRMED: 'ACCOUNTCONFIRMED',
  HOME: 'HOME',
  EDITPROFILE: 'EDITPROFILE',
  DRAWER: 'DRAWER',
  ADDCOMPANYPROFILE: 'ADDCOMPANYPROFILE',
  COMPANYPUBLICVIEW: 'COMPANYPUBLICVIEW',
};
