export default {
  HOME: "HOME",
  LOGIN: "LOGIN",
  SIGNUP: "SIGNUP",
  DRAWER: "DRAWER",
  SPLASH: "SPLASH",
  VERIFYOTP: "VERIFYOTP",
  ONBOARDING: "ONBOARDING",
  EDITPROFILE: "EDITPROFILE",
  FORGETPASSWORD: "FORGETPASSWORD",
  ACCOUNTCONFIRMED: "ACCOUNTCONFIRMED",
  ADDCOMPANYPROFILE: "ADDCOMPANYPROFILE",
  COMPANYPUBLICVIEW: "COMPANYPUBLICVIEW",
};
